autodetect ROLE and load production or stim versions  On branch main 	new file:   CARE/hylog_gpg4 	new file:   CARE/test_HYLOG_GPG 	modified:   init/custom_hyl.init 	modified:   make.package

diff --git a/init/custom_hyl.init b/init/custom_hyl.init
--- a/init/custom_hyl.init
+++ b/init/custom_hyl.init
@@ -1,6 +1,9 @@
 #!/bin/sh
 
 
+hyl_config_production() {
+	echo +++ hyl_config_production
+
 cat - >/etc/inetd.hyl.conf <<EOF
 61001 stream tcp nowait root HY-comm HY-comm dummy
 61002 stream tcp nowait root HY-stat HY-stat dummy
@@ -38,3 +41,32 @@ echo +++ $EARLY complete
 	echo +++ $ONBOOT complete
 ) &
 
+}
+
+hyl_config_stim() {
+	echo +++ hyl_config_stim
+	
+	STIM_INIT=/mnt/local/test_HYLOG_GPG
+	if [ -e $STIM_INIT ]; then
+		echo "HY STIM running $STIM_INIT"
+		cd $(dirname $STIM_INIT)
+		$STIM_INIT
+		return
+	fi
+	STIM_INIT=/usr/local/CARE/test_HYLOG_GPG
+	if [ -e $STIM_INIT ]; then
+		echo "HY STIM running $STIM_INIT"
+		cd $(dirname $STIM_INIT)
+		$STIM_INIT
+		return
+	fi
+	echo "ERROR NO STIM INIT FOUND"	
+}
+
+
+grep QEN /tmp/fpga_status
+if [ $? -eq 0 ]; then
+	hyl_config_production
+else
+	hyl_config_stim
+fi
